### ISSUE TITLE
Allow setting resources.requests.memory so Tower gets enough memory

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/tower-operator#10]
CPU is one thing, but memory is another; without enough, Tower kind of implodes. In the official installer, they set the following defaults for `spec.containers.resources.requests`:

```yaml
web_mem_request: 1
web_cpu_request: 500

task_mem_request: 2
task_cpu_request: 1500
```

They also request quite a bit of memory for RabbitMQ, though at this point I'm inclined to leave it unspecified. I have been running everything under a local minikube cluster with 6G of total RAM available inside, and things run smoothly enough at least for demonstration/light usage. So I don't want to jam requirements in that makes it impossible to run on a workstation with less than 16 GB of RAM available.
